"""init

Revision ID: 702526115658
Revises: f38775d0247c
Create Date: 2026-04-06 00:32:35.689000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702526115658'
down_revision: Union[str, Sequence[str], None] = 'f38775d0247c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guardian_user_id', sa.String(), nullable=False),
    sa.Column('elder_user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['elder_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_id'), 'letters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_id'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
