"""init

Revision ID: 89e9b1797862
Revises: e9ba4a4d4b8b
Create Date: 2026-04-06 13:10:16.022905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e9b1797862'
down_revision: Union[str, Sequence[str], None] = 'e9ba4a4d4b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('guardian_user_id', sa.String(), nullable=False),
    sa.Column('elder_user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link_code', sa.String(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('guardian_user_id', 'elder_user_id', 'created_at', 'link_code')
    )
    op.create_index(op.f('ix_letters_created_at'), 'letters', ['created_at'], unique=False)
    op.create_index(op.f('ix_letters_elder_user_id'), 'letters', ['elder_user_id'], unique=False)
    op.create_index(op.f('ix_letters_guardian_user_id'), 'letters', ['guardian_user_id'], unique=False)
    op.create_index(op.f('ix_letters_link_code'), 'letters', ['link_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_link_code'), table_name='letters')
    op.drop_index(op.f('ix_letters_guardian_user_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_elder_user_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_created_at'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
