"""init

Revision ID: 9dc21c764321
Revises: ffd5a912b40c
Create Date: 2026-04-05 19:14:58.820576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dc21c764321'
down_revision: Union[str, Sequence[str], None] = 'ffd5a912b40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elder_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('elder_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_elder_profiles_user_id'), table_name='elder_profiles')
    op.create_unique_constraint(None, 'elder_profiles', ['user_id'])
    op.add_column('guardian_links', sa.Column('link_code', sa.String(), nullable=False))
    op.add_column('guardian_links', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('guardian_links', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('guardian_links', 'guardian_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guardian_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_guardian_links_elder_user_id'), table_name='guardian_links')
    op.drop_index(op.f('ix_guardian_links_guardian_user_id'), table_name='guardian_links')
    op.create_index(op.f('ix_guardian_links_link_code'), 'guardian_links', ['link_code'], unique=True)
    op.alter_column('users', 'birth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_link_code'), table_name='users')
    op.drop_column('users', 'link_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('link_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_link_code'), 'users', ['link_code'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'birth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_guardian_links_link_code'), table_name='guardian_links')
    op.create_index(op.f('ix_guardian_links_guardian_user_id'), 'guardian_links', ['guardian_user_id'], unique=False)
    op.create_index(op.f('ix_guardian_links_elder_user_id'), 'guardian_links', ['elder_user_id'], unique=False)
    op.alter_column('guardian_links', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('guardian_links', 'guardian_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('guardian_links', 'updated_at')
    op.drop_column('guardian_links', 'is_used')
    op.drop_column('guardian_links', 'link_code')
    op.drop_constraint(None, 'elder_profiles', type_='unique')
    op.create_index(op.f('ix_elder_profiles_user_id'), 'elder_profiles', ['user_id'], unique=False)
    op.alter_column('elder_profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('elder_profiles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
