"""init

Revision ID: b60cac46f0fe
Revises: 702526115658
Create Date: 2026-04-06 00:39:09.612387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60cac46f0fe'
down_revision: Union[str, Sequence[str], None] = '702526115658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('link_code', sa.String(), nullable=False))
    op.add_column('letters', sa.Column('sender_role', sa.String(), nullable=False))
    op.create_index(op.f('ix_letters_link_code'), 'letters', ['link_code'], unique=False)
    op.create_foreign_key(None, 'letters', 'guardian_links', ['link_code'], ['link_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'letters', type_='foreignkey')
    op.drop_index(op.f('ix_letters_link_code'), table_name='letters')
    op.drop_column('letters', 'sender_role')
    op.drop_column('letters', 'link_code')
    # ### end Alembic commands ###
