"""init

Revision ID: cf9fa9685257
Revises: 
Create Date: 2026-04-05 16:24:24.359770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9fa9685257'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('link_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_link_code'), 'users', ['link_code'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('elder_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('medications', sa.String(), nullable=True),
    sa.Column('diseases', sa.String(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('doctor_contact', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elder_profiles_id'), 'elder_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_elder_profiles_user_id'), 'elder_profiles', ['user_id'], unique=False)
    op.create_table('guardian_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guardian_user_id', sa.String(), nullable=False),
    sa.Column('elder_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['elder_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_links_elder_user_id'), 'guardian_links', ['elder_user_id'], unique=False)
    op.create_index(op.f('ix_guardian_links_guardian_user_id'), 'guardian_links', ['guardian_user_id'], unique=False)
    op.create_index(op.f('ix_guardian_links_id'), 'guardian_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardian_links_id'), table_name='guardian_links')
    op.drop_index(op.f('ix_guardian_links_guardian_user_id'), table_name='guardian_links')
    op.drop_index(op.f('ix_guardian_links_elder_user_id'), table_name='guardian_links')
    op.drop_table('guardian_links')
    op.drop_index(op.f('ix_elder_profiles_user_id'), table_name='elder_profiles')
    op.drop_index(op.f('ix_elder_profiles_id'), table_name='elder_profiles')
    op.drop_table('elder_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_link_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
