"""init

Revision ID: eb13e2f4ea99
Revises: b60cac46f0fe
Create Date: 2026-04-06 12:57:17.711144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb13e2f4ea99'
down_revision: Union[str, Sequence[str], None] = 'b60cac46f0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_link_code'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guardian_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('elder_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('link_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['elder_user_id'], ['users.id'], name=op.f('letters_elder_user_id_fkey')),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], name=op.f('letters_guardian_user_id_fkey')),
    sa.ForeignKeyConstraint(['link_code'], ['guardian_links.link_code'], name=op.f('letters_link_code_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('letters_pkey'))
    )
    op.create_index(op.f('ix_letters_link_code'), 'letters', ['link_code'], unique=False)
    op.create_index(op.f('ix_letters_id'), 'letters', ['id'], unique=False)
    # ### end Alembic commands ###
